# This file is generated by cargo2rulesmk.py --run --config cargo2rulesmk.json --features .
# Do not modify this file as changes will be overridden on upgrade.

LOCAL_DIR := $(GET_LOCAL_DIR)
MODULE := $(LOCAL_DIR)
MODULE_CRATE_NAME := cfg_if
MODULE_SRCS := \
	$(LOCAL_DIR)/src/lib.rs \

# NOTE: This crate is a dependency of libstd, so we can't implicitly depend on
# libstd as we would normally. The dependencies listed above are the ones
# declared in the `Cargo.toml` when the `rustc-dep-of-std` feature is enabled.
MODULE_ADD_IMPLICIT_DEPS := false
MODULE_RUST_EDITION := 2018
MODULE_LIBRARY_DEPS := \
	trusty/user/base/lib/libcompiler_builtins-rust \
	trusty/user/base/lib/libcore-rust \

include make/library.mk
